openapi: 3.1.1
info:
  title: Support For Additional Needs API
  version: '0.1.0'
  description: Support For Additional Needs API
  contact:
    name: Learning and Work Progress team
    email: learningandworkprogress@digital.justice.gov.uk
servers:
  - url: https://support-additional-needs-api-dev.hmpps.service.justice.gov.uk
    description: Development
  - url: https://support-additional-needs-api-preprod.hmpps.service.justice.gov.uk
    description: Pre-Production
  - url: https://support-additional-needs-api.hmpps.service.justice.gov.uk
    description: Production
  - url: http://localhost:8080
    description: Local

security:
  - bearerAuth: [ ]

#
# --------------------------------------------------------------------------------
#
paths:
  #
  # --------------------------------------------------------------------------------
  # RESTful style endpoints start here
  # --------------------------------------------------------------------------------
  #

  '/search/prisons/{prisonId}/people':
    get:
      summary: List people in the specified prison, optionally filtering on various prisoner and SAN related fields.
      description: |
        An API that allows searching, filtering and sorting of people in prison and their Additional Needs.
        
        **Role Requirements:**
        Access to this endpoint requires one of the following roles:
          - `ROLE_SUPPORT_ADDITIONAL_NEEDS__SEARCH__RO`
      tags:
        - Search
      operationId: search-by-prison
      parameters:
        - $ref: "#/components/parameters/prisonIdPathParameter"
        - $ref: "#/components/parameters/prisonNameOrNumberQueryStringParameter"
        - $ref: "#/components/parameters/sortByQueryStringParameter"
        - $ref: "#/components/parameters/sortDirectionQueryStringParameter"
        - $ref: "#/components/parameters/pageNumberQueryStringParameter"
        - $ref: "#/components/parameters/pageSizeQueryStringParameter"
      responses:
        '200':
          $ref: '#/components/responses/SearchByPrison'
        '400':
          $ref: '#/components/responses/400Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  #
  # Schema and Enum Definitions
  # --------------------------------------------------------------------------------
  schemas:
    PrisonId:
      type: string
      description: The Prison identifier.
      example: BXI
      pattern: "^[A-Z]{3}$"

    SearchSortField:
      type: string
      enum:
        - PRISONER_NAME
        - PRISON_NUMBER
        - CELL_LOCATION
        - RELEASE_DATE

    SearchSortDirection:
      type: string
      enum:
        - ASC
        - DESC

    ErrorResponse:
      title: ErrorResponse
      description: |
        A generic response body object describing errors in a web request, and can be used to communicate several
        different types of error condition such as (but not limited to) `400 BAD REQUEST`, `409 CONFLICT` etc.
      properties:
        status:
          description: The HTTP status code.
          type: integer
          example: 400
        errorCode:
          description: An optional application specific error code.
          type: string
        userMessage:
          description: An optional human readable description of the error.
          type: string
          example: 'No Action Plan found for prisoner [A1234BC]'
        developerMessage:
          description: An optional error message that may have more technical information for developers.
          type: string
        moreInfo:
          description: Optional more detailed information about the error.
          type: string
      required:
        - status

    SentenceType:
      type: string
      description: An enumeration of prisoner sentence types.
      enum:
        - RECALL
        - DEAD
        - INDETERMINATE_SENTENCE
        - SENTENCED
        - CONVICTED_UNSENTENCED
        - CIVIL_PRISONER
        - IMMIGRATION_DETAINEE
        - REMAND
        - UNKNOWN
        - OTHER

    SearchByPrisonResponse:
      title: SearchByPrisonResponse
      description: Response body containing a Search by prison paginated results response.
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/PaginationMetaData'
        people:
          type: array
          description: A List containing zero or more people matching the search.
          items:
            $ref: '#/components/schemas/Person'
      required:
        - people
        - pagination

    PaginationMetaData:
      description: Pagination metadata for the search results.
      type: object
      properties:
        totalElements:
          type: integer
          description: Total number of elements matching the criteria
          example: 100
        totalPages:
          type: integer
          description: Total number of pages
          example: 5
        page:
          type: integer
          description: Current page number
          example: 2
        last:
          type: boolean
          description: Indicates this is the last page
          example: false
        first:
          type: boolean
          description: Indicates this is the first page
          example: false
        pageSize:
          type: integer
          description: Number of items per page
          example: 20
      required:
        - totalElements
        - totalPages
        - page
        - last
        - first
        - pageSize

    Person:
      title: Person
      description: A summary of a person in prison, including flags as to whether they have Challenges, Strengths, Conditions or Support Recommendations recorded in the service.
      type: object
      properties:
        forename:
          type: string
          description: The prisoner's forename.
          example: Bob
        surname:
          type: string
          description: The prisoner's surname.
          example: Smith
        prisonNumber:
          type: string
          description: The prisoner's NOMIS number.
          example: A1234BC
        dateOfBirth:
          type: string
          format: date
          description: The prisoner's date of birth.
          example: "1999-12-01"
        cellLocation:
          type: string
          description: The prisoner's cell location within prison
          example: "B-3-047"
        releaseDate:
          type: string
          format: date
          description: The prisoner's release date as returned by prisoner-search-api.
          example: "2035-11-01"
        sentenceType:
          $ref: '#/components/schemas/SentenceType'
          description: The prisoner's sentence type.
        additionalNeeds:
          $ref: '#/components/schemas/AdditionalNeedsSummary'
          description: |
            Optional object containing summary data held in this service about the person.  
            The object is only populated if the person has Additional Needs data in this service.  
            If the person does not yet have any data recorded in this service this field will be null.
      required:
        - forename
        - surname
        - prisonNumber
        - dateOfBirth
        - sentenceType

    AdditionalNeedsSummary:
      title: AdditionalNeedsSummary
      description: A summary of a person's Challenges, Strengths, Conditions or Support Recommendations recorded in the service.
      type: object
      properties:
        hasConditions:
          type: boolean
          description: Whether this person has any Conditions recorded in the service.
          example: true
        hasChallenges:
          type: boolean
          description: Whether this person has any Challenges recorded in the service.
          example: true
        hasStrengths:
          type: boolean
          description: Whether this person has any Strengths recorded in the service.
          example: true
        hasSupportRecommendations:
          type: boolean
          description: Whether this person has any Support Recommendations recorded in the service.
          example: true
      required:
        - hasChallenges
        - hasConditions
        - hasStrengths
        - hasSupportRecommendations

  #
  # Response Body Definitions
  # --------------------------------------------------------------------------------
  responses:
    400Error:
      description: Error response for a HTTP 400 describing fields in the request payload that are in error.
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            status: 400
            userMessage: 'Error on field targetCompletionDate: rejected value [2023-06-01] cannot be in the past'
    404Error:
      description: |
        Error response for a HTTP 404 describing the problem with the request.
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            status: 404
            userMessage: 'The prisoner with prisonNumber=[A1234BC] not found'
    409Error:
      description: |
        Error response for a HTTP 409 describing the problem with the request.
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            status: 409
            userMessage: 'A resource with reference [c88a6c48-97e2-4c04-93b5-98619966447b] has an unexpected status = ARCHIVED'

    SearchByPrison:
      description: Response body containing a Search by prison results response.
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SearchByPrisonResponse'

  #
  # Request Body Definitions
  # --------------------------------------------------------------------------------
  #requestBodies:

  parameters:
    prisonIdPathParameter:
      name: prisonId
      in: path
      required: true
      schema:
        type: string
        pattern: "^[A-Z]{3}$"
        example: "BXI"
      description: The ID of the prison
    prisonNumberPathParameter:
      name: prisonNumber
      description: The NOMIS Prison Reference Number of the Prisoner that the operation is being performed on.
      schema:
        type: string
        pattern: "^[A-Z]\\d{4}[A-Z]{2}$"
        example: 'A1234BC'
      in: path
      required: true
    prisonNameOrNumberQueryStringParameter:
      name: prisonerNameOrNumber
      in: query
      description: Filter by prisoner name or prison number
      schema:
        type: string
        example: 'Bloggs'
    sortByQueryStringParameter:
      name: sortBy
      in: query
      description: Column to sort by
      schema:
        $ref: '#/components/schemas/SearchSortField'
        example: 'PRISONER_NAME'
    sortDirectionQueryStringParameter:
      name: sortDirection
      in: query
      description: Sort direction (ascending or descending)
      schema:
        $ref: '#/components/schemas/SearchSortDirection'
        example: 'ASC'
    pageNumberQueryStringParameter:
      name: page
      in: query
      description: Page number for pagination
      schema:
        type: integer
        minimum: 1
        default: 1
        example: 1
    pageSizeQueryStringParameter:
      name: size
      in: query
      description: Number of items per page
      schema:
        type: integer
        minimum: 1
        default: 50
        example: 50
