package uk.gov.justice.digital.hmpps.supportadditionalneedsapi.specialtests.resource.sar

import org.junit.jupiter.api.BeforeEach
import org.springframework.test.context.ActiveProfiles
import org.springframework.test.web.reactive.server.WebTestClient
import uk.gov.justice.digital.hmpps.subjectaccessrequest.SarIntegrationTestHelper
import uk.gov.justice.digital.hmpps.subjectaccessrequest.SarReportTest
import uk.gov.justice.digital.hmpps.supportadditionalneedsapi.IntegrationTestBase
import uk.gov.justice.digital.hmpps.supportadditionalneedsapi.config.MillisecondTickingClock
import uk.gov.justice.digital.hmpps.supportadditionalneedsapi.randomValidPrisonNumber
import java.time.LocalDate

// Run test with env var SAR_GENERATE_ACTUAL=true to generate actual SAR report content for the test data created in this test,
// which can be used to verify the format and content of the report generated by the Subject Access Request service.

@ActiveProfiles("integration-test", "ticking-clock")
class SarReportGenerationTest :
  IntegrationTestBase(),
  SarReportTest {
  private lateinit var prisonNumber: String

  @BeforeEach
  fun setup() {
    prisonNumber = randomValidPrisonNumber()
    // Reset the TickingClock current tick, which means the test and assertions will survive 999 calls to Instant.now() before the clock ticks over to the next second.
    // This is important because the SAR Report Generation test setup calls Instant.now() multiple times to setup the test data.
    // We need a controlled tick of the clock so that each entity saved is timestamped with an incremental time so that sorting
    // on timestamp works in a predictable manner.
    // But we need to ensure the clock doesn't tick over to the next second as the generated report will then not match the expected report.
    // This is arguably slightly fragile in that the test setup is limited to 999 calls to Instant.now() before it ticks
    // over to the next second (because the precision of the timestamp fields in flyway is `timestamp(3)`), but it should
    // be OK.
    if (clock is MillisecondTickingClock) {
      (clock as MillisecondTickingClock).resetMilliSecondsTick()
    }
  }

  override fun getWebTestClientInstance(): WebTestClient = webTestClient

  override fun getSarHelper(): SarIntegrationTestHelper = sarIntegrationTestHelper

  override fun getPrn(): String = prisonNumber

  override fun setupTestData() {
    stubGetDisplayName("testuser")
    anElSPExists(
      prisonNumber = prisonNumber,
      lnspSupport = null,
      lnspSupportHours = null,
    )
    aValidSupportStrategyExists(prisonNumber)
    aValidStrengthExists(prisonNumber)
    aValidChallengeExists(prisonNumber)
    aValidAlnScreenerExists(prisonNumber, screeningDate = LocalDate.parse("2026-02-15"))
      .also { aValidStrengthExists(prisonNumber, it.id) }
      .also { aValidChallengeExists(prisonNumber, it.id) }
    aValidAlnScreenerExists(prisonNumber, screeningDate = LocalDate.parse("2026-01-10"))
      .also { aValidStrengthExists(prisonNumber, it.id) }
      .also { aValidChallengeExists(prisonNumber, it.id) }
    aValidPlanCreationScheduleExists(prisonNumber, deadlineDate = LocalDate.parse("2026-03-15"))
    val reviewSchedule = aValidReviewScheduleExists(prisonNumber, deadlineDate = LocalDate.parse("2026-04-15"))
    aValidConditionExists(prisonNumber)
    aValidAlnAssessmentExists(prisonNumber, screeningDate = LocalDate.parse("2026-01-05"), hasNeed = false)
    aValidAlnAssessmentExists(prisonNumber, screeningDate = LocalDate.parse("2026-02-05"), hasNeed = true)
    // Update the EHCP answer, creating a second EHCP version, to exercise the EHCP section's iteration
    anEhcpStatusUpdateExists(prisonNumber, hasCurrentEhcp = false)
    // A review, which updates the plan (creating the plan history version paired with the review)
    aPlanReviewExists(
      prisonNumber,
      reviewScheduleReference = reviewSchedule.reference,
      teachingAdjustments = "teachingAdjustmentsUpdated",
      detail = "detailUpdated",
      lnspSupport = "LNSP support required",
      lnspSupportHours = 5,
      otherContributors = listOf("Jane Doe" to "Mentor"),
    )
  }
}
