package uk.gov.justice.digital.hmpps.supportadditionalneedsapi.resource.sar

import org.junit.jupiter.api.BeforeEach
import org.springframework.test.web.reactive.server.WebTestClient
import uk.gov.justice.digital.hmpps.subjectaccessrequest.SarIntegrationTestHelper
import uk.gov.justice.digital.hmpps.subjectaccessrequest.SarReportTest
import uk.gov.justice.digital.hmpps.supportadditionalneedsapi.IntegrationTestBase
import uk.gov.justice.digital.hmpps.supportadditionalneedsapi.domain.entity.PlanCreationScheduleStatus
import uk.gov.justice.digital.hmpps.supportadditionalneedsapi.randomValidPrisonNumber
import java.time.LocalDate

// Run test with env var SAR_GENERATE_ACTUAL=true to generate actual SAR report content for the test data created in this test,
// which can be used to verify the format and content of the report generated by the Subject Access Request service.

class SarReportGenerationTest :
  IntegrationTestBase(),
  SarReportTest {
  private lateinit var prisonNumber: String

  @BeforeEach
  fun setup() {
    prisonNumber = randomValidPrisonNumber()
  }

  override fun getWebTestClientInstance(): WebTestClient = webTestClient

  override fun getSarHelper(): SarIntegrationTestHelper = sarIntegrationTestHelper

  override fun getPrn(): String = prisonNumber

  override fun setupTestData() {
    stubGetDisplayName("testuser")
    anElSPExists(prisonNumber)
    aValidChallengeExists(prisonNumber)
    aValidStrengthExists(prisonNumber)
    aValidConditionExists(prisonNumber)
    aValidPlanCreationScheduleExists(prisonNumber, status = PlanCreationScheduleStatus.COMPLETED)
    val reviewScheduleEntity = aValidReviewScheduleExists(prisonNumber, deadlineDate = LocalDate.now().plusMonths(1))
    aValidReviewExists(prisonNumber, reviewScheduleEntity.reference)
    val screener = aValidAlnScreenerExists(prisonNumber)
    aValidChallengeExists(prisonNumber, screenerId = screener.id)
    aValidStrengthExists(prisonNumber, screenerId = screener.id)
  }
}
